export type StyleGroupKey = "basic" | "images" | "blocks" | "tables";

export type StyleNodeKind = "heading" | "paragraph" | "block" | "code" | "list" | "image" | "table";

export type HorizontalAlign = "left" | "center" | "right" | "justify";
export type VerticalAlign = "top" | "middle" | "bottom";
export type TableLayoutMode = "auto" | "fixed";
export type BorderStyleMode = "solid" | "dashed" | "dotted" | "double" | "none";
export type ColumnWidthMode = "auto" | "custom";
export type TablePresetKey = "business" | "official" | "grid" | "striped";
export type CodeBlockPresetKey = "document" | "terminal" | "blueprint" | "minimal";
export type ListLevelType = "bullet" | "number";
export type ListMarkerStyle = "disc" | "circle" | "square" | "triangle" | "dash" | "check" | "bar" | "double-bar" | "triple-bar";
export type ListWrapMode = "flat" | "hanging";
export type ListNumberingMode = "restart" | "continue";
export type CaptionPosition = "above" | "below";
export type ImageWidthMode = "content" | "original" | "custom";
export type MarkdownHeadingStyleId = "heading-1" | "heading-2" | "heading-3" | "heading-4" | "heading-5" | "heading-6";
export type WordHeadingTarget = "title" | MarkdownHeadingStyleId;

export type StyleNode = {
  id: string;
  name: string;
  displayName: string;
  group: StyleGroupKey;
  kind: StyleNodeKind;
  markdown: string;
  description: string;
  warning?: string;
};

export type StyleDraft = {
  styleId: string;
  chineseFont: string;
  latinFont: string;
  fontSize: number;
  fontWeight: string;
  color: string;
  lineHeight: string;
  firstLineIndent: number;
  beforeSpacing: number;
  afterSpacing: number;
  align: HorizontalAlign;
  autoNumbering: boolean;
  numberFormat: string;
  listMarkerStyle: ListMarkerStyle;
  listIndent: number;
  listTextIndent: number;
  listWrapMode: ListWrapMode;
  listNumberingMode: ListNumberingMode;
  nestedLevel2MarkerStyle: ListMarkerStyle;
  nestedLevel3MarkerStyle: ListMarkerStyle;
  nestedLevel2NumberFormat: string;
  nestedLevel3NumberFormat: string;
  listLevel1Type: ListLevelType;
  listLevel2Type: ListLevelType;
  listLevel3Type: ListLevelType;
  listLevel4Type: ListLevelType;
  listLevel1MarkerStyle: ListMarkerStyle;
  listLevel2MarkerStyle: ListMarkerStyle;
  listLevel3MarkerStyle: ListMarkerStyle;
  listLevel4MarkerStyle: ListMarkerStyle;
  listLevel1NumberFormat: string;
  listLevel2NumberFormat: string;
  listLevel3NumberFormat: string;
  listLevel4NumberFormat: string;
  listLevel1ChineseFont: string;
  listLevel2ChineseFont: string;
  listLevel3ChineseFont: string;
  listLevel4ChineseFont: string;
  listLevel1LatinFont: string;
  listLevel2LatinFont: string;
  listLevel3LatinFont: string;
  listLevel4LatinFont: string;
  listLevel1FontSize: number;
  listLevel2FontSize: number;
  listLevel3FontSize: number;
  listLevel4FontSize: number;
  listLevel1FontWeight: string;
  listLevel2FontWeight: string;
  listLevel3FontWeight: string;
  listLevel4FontWeight: string;
  listLevel1Color: string;
  listLevel2Color: string;
  listLevel3Color: string;
  listLevel4Color: string;
  listLevel1LineHeight: string;
  listLevel2LineHeight: string;
  listLevel3LineHeight: string;
  listLevel4LineHeight: string;
  listLevel1BeforeSpacing: number;
  listLevel2BeforeSpacing: number;
  listLevel3BeforeSpacing: number;
  listLevel4BeforeSpacing: number;
  listLevel1AfterSpacing: number;
  listLevel2AfterSpacing: number;
  listLevel3AfterSpacing: number;
  listLevel4AfterSpacing: number;
  listLevel1Align: HorizontalAlign;
  listLevel2Align: HorizontalAlign;
  listLevel3Align: HorizontalAlign;
  listLevel4Align: HorizontalAlign;
  listLevel1Indent: number;
  listLevel2Indent: number;
  listLevel3Indent: number;
  listLevel4Indent: number;
  listLevel1TextIndent: number;
  listLevel2TextIndent: number;
  listLevel3TextIndent: number;
  listLevel4TextIndent: number;
  listLevel1WrapMode: ListWrapMode;
  listLevel2WrapMode: ListWrapMode;
  listLevel3WrapMode: ListWrapMode;
  listLevel4WrapMode: ListWrapMode;
  listLevel1NumberingMode: ListNumberingMode;
  listLevel2NumberingMode: ListNumberingMode;
  listLevel3NumberingMode: ListNumberingMode;
  listLevel4NumberingMode: ListNumberingMode;
  nestedIndentStep: number;
  backgroundColor: string;
  quoteBorderColor: string;
  quoteBorderWidth: number;
  codeBlockPreset: CodeBlockPresetKey;
  codeBorderColor: string;
  codeBorderRadius: number;
  codePaddingX: number;
  codePaddingY: number;
  tableLayout: TableLayoutMode;
  fitToPageWidth: boolean;
  tableWidthPercent: number;
  tableHorizontalAlign: Exclude<HorizontalAlign, "justify">;
  columnWidthMode: ColumnWidthMode;
  firstColumnWidth: number;
  secondColumnWidth: number;
  thirdColumnWidth: number;
  cellPaddingX: number;
  cellPaddingY: number;
  cellWrap: boolean;
  minRowHeight: number;
  rowStripe: boolean;
  borderStyle: BorderStyleMode;
  borderColor: string;
  borderWidth: number;
  borderTopWidth: number;
  borderRightWidth: number;
  borderBottomWidth: number;
  borderLeftWidth: number;
  headerBorderColor: string;
  headerBorderWidth: number;
  bodyBorderColor: string;
  bodyBorderWidth: number;
  outerBorderStrong: boolean;
  showInnerVerticalBorder: boolean;
  showInnerHorizontalBorder: boolean;
  headerBold: boolean;
  headerAlign: Exclude<HorizontalAlign, "justify">;
  headerVerticalAlign: VerticalAlign;
  headerBackgroundColor: string;
  headerFontSize: number;
  headerLineHeight: string;
  bodyAlign: Exclude<HorizontalAlign, "justify">;
  bodyVerticalAlign: VerticalAlign;
  bodyFontSize: number;
  bodyLineHeight: string;
  bodyBackgroundColor: string;
  captionAlign: Exclude<HorizontalAlign, "justify">;
  captionNumbering: boolean;
  captionPosition: CaptionPosition;
  captionNumberFormat: string;
  imageAlign: Exclude<HorizontalAlign, "justify">;
  imageWidthMode: ImageWidthMode;
  imageWidthPercent: number;
  tablePreset: TablePresetKey;
};

export type PaperSize = "A3" | "A4" | "A5" | "A6" | "B4" | "B5" | "B6" | "Letter" | "Legal" | "Executive" | "Tabloid" | "K16" | "K32";
export type FooterPageNumberFormat = "page" | "plain" | "page-total" | "plain-total" | "dash" | "none";
export type TocLeaderStyle = "dot" | "cjk-dot" | "dot-spaced" | "dash" | "line" | "space";

export type PageSettingsDraft = {
  paperSize: PaperSize;
  orientation: "portrait" | "landscape";
  marginTop: number;
  marginBottom: number;
  marginLeft: number;
  marginRight: number;
  headerEnabled: boolean;
  headerText: string;
  footerEnabled: boolean;
  footerText: string;
  footerPageNumberFormat: FooterPageNumberFormat;
  footerStartPage: number;
  tocEnabled: boolean;
  tocDepth: string;
  tocLeader: TocLeaderStyle;
  tocShowPageNumbers: boolean;
};

export type MarkdownFeatureSettings = {
  inlineCode: boolean;
  codeBlock: boolean;
  quoteBlock: boolean;
  horizontalRule: boolean;
};

export type MarkdownRulesSettings = {
  headingMappings: Record<MarkdownHeadingStyleId, WordHeadingTarget>;
};

export type TemplateStyleConfig = {
  templateId: string;
  styles: Record<string, StyleDraft>;
  pageSettings: PageSettingsDraft;
  markdownFeatures: MarkdownFeatureSettings;
  markdownRules: MarkdownRulesSettings;
  updatedAt: string;
};
